name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  api:
    name: API checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sais/api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Validate sources
        run: python -m compileall app
      - name: Run tests
        run: pytest

  web:
    name: Web lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sais/web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint -- --no-color

  docker:
    name: Docker build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sais
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build API image
        run: docker build -f ops/docker/api.Dockerfile -t sais-api-ci .
      - name: Build web image
        run: docker build -f ops/docker/web.Dockerfile -t sais-web-ci .
      - name: Build worker image
        run: docker build -f ops/docker/worker.Dockerfile -t sais-worker-ci .
      - name: Validate docker compose configuration
        run: docker compose -f docker-compose.yml config -q
